version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Go tests
          command: docker-compose run --rm api make
      - codecov/upload:
          file: ./src/coverage.txt

  cloudgov:
    machine: true
    steps:
      - checkout
      - deploy:
          command: ./bin/deploy-cloudgov

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test
      - cloudgov:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
