version: 2.1
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Code Climate reporter
          command: ./bin/setup-codeclimate
      - run:
          name: Run Go tests
          command: docker-compose run --rm api make
      - run:
          name: Upload test coverage to Code Climate
          command: ./bin/upload-codeclimate
      - run:
          name: Upload test coverage to Codecov
          command: ./bin/upload-codecov

  cloudgov:
    machine: true
    steps:
      - checkout
      - deploy:
          command: ./bin/deploy-cloudgov

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test
      - cloudgov:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
